ksu_website/config/routes.rb
KsuWebsite::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"  
  resources :sessions, only: [:create]  
  resources :users, only: [:create]
  
  resources :courses, only: [:index]
  resources :employments, only: [:index]
  resources :faculties, only: [:index]
  resources :clubs, only: [:index]
  resources :events, only: [:index]
  
  namespace :admin do 
    get '', to: 'dashboard#index', as: '/' 
	resources :courses
    resources :employments
    resources :faculties
    resources :clubs
    resources :events
	resources :users
  end

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  get '/welcome', to: 'welcome#index'
  get '/about', to: 'about#index'
  get '/courses', to: 'courses#index'
  get '/employments', to: 'employments#index'
   
   
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

ksu_website/app/models/club.rb
class Club < ActiveRecord::Base
  include Filterable
  
  validates :name, presence: true, length: {minimum: 1, maximum: 50}, uniqueness: true
  validates :url, length: {minimum: 1, maximum: 100}, format: { without: /\s/ }  # No spaces; URLs can also be omitted
  validates :description, presence: true, length: {minimum: 1, maximum: 1000}
  validates :meeting, presence: true, length: {minimum: 1, maximum: 50}
  
  # Select scopes, used for search
  scope :name_keywords, ->(keywords) { where "name like ?", "%#{keywords}%" }
end

ksu_website/app/controllers/admin/clubs_controller.rb
class Admin::ClubsController < AdminController
  before_action :set_club, only: [:show, :edit, :update, :destroy]
  
  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.filter(search_params.slice(:name_keywords))
  end
  
  # GET /clubs/1
  # GET /clubs/1.json
  def show
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to admin_club_path(@club), notice: 'Club was successfully created.' }
        format.json { render action: 'show', status: :created, location: @club }
      else
        format.html { render action: 'new' }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to admin_club_path(@club), notice: 'Club was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to admin_clubs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:name, :description, :url, :meeting)
    end
	
	# Gets trusted parameters for search form
	def search_params
	  params.permit(:name_keywords)
	end
end

ksu_website/app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  #before_action :set_club, only: [:show, :edit, :update, :destroy]
  
  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.filter(search_params.slice(:name_keywords))
  end
 
  private
	# Gets trusted parameters for search form
	def search_params
	  params.permit(:name_keywords)
	end
end

ksu_website/app/helpers/clubs_helper.rb
module ClubsHelper
end

ksu_website/app/views/clubs/_form.html.erb
<%= form_for(@club) do |f| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :meeting %><br>
    <%= f.text_field :meeting %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ksu_website/app/views/clubs/index.html.erb
<html>
<head>
<%=render "/layouts/header" %>
</head>
<body>
	<div id="main-wrapper">
		<div id="main">
			<h3>Search</h3>
			<%= form_tag clubs_path, method: "get" do %>
			<%= label_tag("Name: ") %> <%= text_field_tag :name_keywords %> <br/>
			<%= submit_tag "Enter" %>
			<% end %>
			<br><br>




			<div class="panel-group" id="accordion">
				<% for club in @clubs %>
					<div class="panel panel-default">
						<div class="panel-heading accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#<%=club.name.gsub(/[^0-9A-Za-z]/, '')%>">
							<div class="panel-title">
								<h3>
									<%= club.name%>
								</h3>
							</div>
						</div>
						<div id="<%=club.name.gsub(/[^0-9A-Za-z]/, '')%>" class="panel-collapse collapse out">
							<div class="panel-body"> <i>Description: </i> <%= club.description %> </div>
						</div>
					</div>
				<% end %>
			</div>
				
		</div>
	</div>
</body>
</html>