ksu_website/config/routes.rb
KsuWebsite::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"  
  resources :sessions, only: [:create]  
  resources :users, only: [:create]
  
  resources :courses, only: [:index]
  resources :employments, only: [:index]
  resources :faculties, only: [:index]
  resources :clubs, only: [:index]
  resources :events, only: [:index]
  
  namespace :admin do 
    get '', to: 'dashboard#index', as: '/' 
	resources :courses
    resources :employments
    resources :faculties
    resources :clubs
    resources :events
	resources :users
  end

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  get '/welcome', to: 'welcome#index'
  get '/about', to: 'about#index'
  get '/courses', to: 'courses#index'
  get '/employments', to: 'employments#index'
   
   
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

ksu_website/app/models/event.rb
class Event < ActiveRecord::Base
  include Filterable

  validates :event_date, presence: true
  validates :title, presence: true, length: {minimum: 1, maximum: 50}
  validates :location, presence: true, length: {minimum: 1, maximum: 50}
  validates :description, presence: true, length: {minimum: 1, maximum: 200}
  
  # Select scopes, used for search
  scope :title_keywords, ->(keywords) { where("title like ?", "%#{keywords}%") }
  scope :chosen_date, ->(chosen_date) { where 'event_date' => DateTime.new(chosen_date.year,chosen_date.month,1)..(DateTime.new(chosen_date.year,chosen_date.month,1) + 1.month)  }
  scope :free_food_select, ->(free_food_select) { where free_food: true }
end

ksu_website/app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
	@events = Event.filter(search_params.slice(:title_keywords, :free_food_select))
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to admin_event_path(@event), notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to admin_event_path(@event), notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to admin_events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :event_date, :location, :description, :free_food)
    end
	
	# Gets trusted parameters for search form
	def search_params
	  params.permit(:title_keywords, :free_food_select)
	end
end

ksu_website/app/controllers/events_controller.rb
class EventsController < ApplicationController
  #before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
	@events = Event.filter(search_params.slice(:title_keywords, :chosen_date, :free_food_select))
    if @events[0] == nil
	  @search_date = Date.today
	else
	  @search_date = @events[0].event_date.to_date
	end
  end

  private
	# Gets trusted parameters for search form
	def search_params
	  new_date = Date.today  # Default value
	  if(params[:chosen_date])
	    choice = params[:chosen_date]
	    new_date = Date.new(choice["date(1i)"].to_i, choice["date(2i)"].to_i, 1)
	  end
	  
	  { title_keywords: params[:title_keywords], chosen_date: new_date, free_food_select: params[:free_food_select] } 
	end
end

ksu_website/app/helpers/events_helper.rb
module EventsHelper
end

ksu_website/app/views/admin/events/_form.html.erb
<%= form_for([:admin,@event]) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :event_date %><br>
    <%= f.datetime_select :event_date %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label "Free Food" %><br>
    <%= f.check_box :free_food %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ksu_website/app/views/admin/events/edit.html.erb
<html>
<head>
<%=render "/layouts/header" %>
</head>
<body>
<div id="main-wrapper">
<div id="main">

  <h1>Editing event</h1>

  <%= render 'form' %>

  <%= link_to 'Show', admin_event_path(@event) %> |
  <%= link_to 'Back', admin_events_path %>

</div>
</div>
</body>
</html>

ksu_website/app/views/admin/events/index.html.erb
<html>
<head>
<%=render "/layouts/header" %>
<style type = "text/css">
    table, td, th {
      border: 1px solid black;
	  padding: 15px;
    } 
	th {
	  background-color: rgb(149, 29, 209);
      color:white
	}
</style>
</head>
<body>
<div id="main-wrapper">
<div id="main">

  <h1>Listing Events</h1>

  <h3>Search</h3>
  <%= form_tag admin_events_path, method: "get" do %>
    <%= label_tag("Title: ") %> <%= text_field_tag :title_keywords %> <br/>
    <%= label_tag("Free Food:") %> <%= check_box_tag :free_food_select %> <br/>
    <%= submit_tag "Enter" %>
  <% end %>
  </br>
  
  <%= link_to 'New Event', new_admin_event_path %>
  </br></br>
	
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Title</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @events.order(:event_date).each do |event| %>
        <tr>
          <td><%= event.event_date.strftime("%B %d, %Y") %></td>
          <td><%= event.title %></td>
          <td><%= link_to 'Show', admin_event_path(event) %></td>
          <td><%= link_to 'Edit', edit_admin_event_path(event) %></td>
          <td><%= link_to 'Destroy', admin_event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br/>

</div>
</div>
</body>
</html>

ksu_website/app/views/admin/events/new.html.erb
<html>
<head>
<%=render "/layouts/header" %>
</head>
<body>
<div id="main-wrapper">
<div id="main">

  <h1>New event</h1>

  <%= render 'form' %>

  <%= link_to 'Back', admin_events_path %>

</div>
</div>
</body>
</html>

ksu_website/app/views/admin/events/show.html.erb
<html>
<head>
<%=render "/layouts/header" %>
</head>
<body>
<div id="main-wrapper">
<div id="main">

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @event.title %>
  </p>

  <p>
    <strong>Event date:</strong>
    <%= @event.event_date %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= @event.location %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @event.description %>
  </p>

  <p>
    <strong>Free Food:</strong>
    <%= @event.free_food %>
  </p>

  <%= link_to 'Edit', edit_admin_event_path(@event) %> |
  <%= link_to 'Back', admin_events_path %>

</div>
</div>
</body>
</html>