ksu_website/config/routes.rb
KsuWebsite::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"  
  resources :sessions, only: [:create]  
  resources :users, only: [:create]
  
  resources :courses, only: [:index]
  resources :employments, only: [:index]
  resources :faculties, only: [:index]
  resources :clubs, only: [:index]
  resources :events, only: [:index]
  
  namespace :admin do 
    get '', to: 'dashboard#index', as: '/' 
	resources :courses
    resources :employments
    resources :faculties
    resources :clubs
    resources :events
	resources :users
  end

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  get '/welcome', to: 'welcome#index'
  get '/about', to: 'about#index'
  get '/courses', to: 'courses#index'
  get '/employments', to: 'employments#index'
   
   
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

ksu_website/app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  def is_admin?
    return self.admin
  end
  
end

ksu_website/app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @users = User.all
  end
  
  def show
  end

  def new
    @user = User.new
  end
  
  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_path(@user)
    else
	  render "new"
    end
  end
  
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
  
	def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :admin)
    end
end

ksu_website/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
	  render "new"
    end
  end
  
  private
	def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

ksu_website/app/helpers/users_helper.rb
module UsersHelper
end

ksu_website/app/views/admin/users/_form.html.erb
<%= form_for([:admin,@user]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :admin %><br />
	<%= f.check_box :admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ksu_website/app/views/admin/users/edit.html.erb
<html>
<head>
  <%=render "/layouts/header" %>
</head>
<body>
<div id="main-wrapper">
<div id="main">

<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

</div>
</div>
</body>
</html>

ksu_website/app/views/admin/users/index.html.erb
<html>
<head>
  <%=render "/layouts/header" %>
  <style type = "text/css">
    table, td, th {
      border: 1px solid black;
	  padding: 15px;
    } 
	th {
	  background-color: rgb(149, 29, 209);
      color:white
	}
</style>
</head>
<body>
<div id="main-wrapper">
	<div id="main">

	<h1>Listing Users</h1>
	</br>

	<%= link_to 'Add User', new_admin_user_path %>
	</br></br>

	<table>
	  <thead>
		<tr>
		  <th>Email</th>
		  <th></th>
		  <th></th>
		  <th></th>
		</tr>
	  </thead>

	  <tbody>
		<% @users.each do |user| %>
		  <tr>
			<td><%= user.email %></td>
			<td><%= link_to "Show", admin_user_path(user) %></td>
			<td><%= link_to "Edit", edit_admin_user_path(user) %></td>
			<td><%= link_to "Destroy", admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
		  </tr>
		<% end %>
	  </tbody>
	</table>

	<br>

	</div>
</div>
</body>
</html>

ksu_website/app/views/admin/users/new.html.erb
<html>
<head>
<%=render "/layouts/header" %>
</head>
<body>
<div id="main-wrapper">
<div id="main">

  <h1>Create User</h1>

  <%= render 'form' %>

  <%= link_to 'Back', admin_users_path %>
  
</div>
</div>
</body>
</html>

ksu_website/app/views/admin/users/show.html.erb
<html>
<head>
<%=render "/layouts/header" %>
</head>
<body>
<div id="main-wrapper">
<div id="main">

<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

</div>
</div>
</body>
</html>